package com.dmv.footballheadz.game.impl;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;
import java.util.Objects;

@DynamoDBTable(tableName = "Game")
public class Game implements Serializable {

    private static final long serialVersionUID = -3534650012619938612L;

    private String id;
    private String year;
    private String week;
    private String homeTeam;
    private String awayTeam;
    private Double homeTeamPts;
    private Double awayTeamPts;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Game withId(String id) {
        setId(id);
        return this;
    }

    @DynamoDBAttribute(attributeName ="Year")
    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public Game withYear(String year) {
        setYear(year);
        return this;
    }

    @DynamoDBAttribute(attributeName ="Week")
    public String getWeek() {
        return week;
    }

    public void setWeek(String week) {
        this.week = week;
    }

    public Game withWeek(String week) {
        setWeek(week);
        return this;
    }

    @DynamoDBAttribute(attributeName ="HomeTeam")
    public String getHomeTeam() {
        return homeTeam;
    }

    public void setHomeTeam(String homeTeam) {
        this.homeTeam = homeTeam;
    }

    public Game withHomeTeam(String homeTeam) {
        setHomeTeam(homeTeam);
        return this;
    }

    @DynamoDBAttribute(attributeName ="AwayTeam")
    public String getAwayTeam() {
        return awayTeam;
    }

    public void setAwayTeam(String awayTeam) {
        this.awayTeam = awayTeam;
    }

    public Game withAwayTeam(String awayTeam) {
        setAwayTeam(awayTeam);
        return this;
    }

    @DynamoDBAttribute(attributeName ="HomeTeamPts")
    public Double getHomeTeamPts() {
        return homeTeamPts;
    }

    public void setHomeTeamPts(Double homeTeamPts) {
        this.homeTeamPts = homeTeamPts;
    }

    public Game withHomeTeamPts(Double homeTeamPts) {
        setHomeTeamPts(homeTeamPts);
        return this;
    }

    @DynamoDBAttribute(attributeName ="AwayTeamPts")
    public Double getAwayTeamPts() {
        return awayTeamPts;
    }

    public void setAwayTeamPts(Double awayTeamPts) {
        this.awayTeamPts = awayTeamPts;
    }

    public Game withAwayTeamPts(Double awayTeamPts) {
        setAwayTeamPts(awayTeamPts);
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Game)) return false;
        Game game = (Game) o;
        return id.equals(game.id) && Objects.equals(year, game.year) && Objects.equals(week, game.week) && Objects.equals(homeTeam, game.homeTeam) && Objects.equals(awayTeam, game.awayTeam) && Objects.equals(homeTeamPts, game.homeTeamPts) && Objects.equals(awayTeamPts, game.awayTeamPts);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, year, week, homeTeam, awayTeam, homeTeamPts, awayTeamPts);
    }
}
